all: compiler clean team
compiler:	trylex.l
	lex trylex.l
	gcc lex.yy.c
clean:
	rm -f lex.yy.c
team:
	echo "Team: ksanu1998\n\nK. Sai Anuroop\n170030035@iitdh.ac.in\n\nHarshal Gajjar\n160010003@iitdh.ac.in"